jobs:
  include:
    - stage: lint
      language: node_js
      node_js: 12
      before_install:
        - cd frontend
      install:
        - yarn
      script:
        - yarn type-check
        - yarn tslint
        - yarn sasslint
    - language: java
      java: 11
      before_install:
        - cd backend
        - chmod +x ./gradlew
      install:
        - ./gradlew
      script:
        - ./gradlew checkstyleMain
